### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by nico-shimo** [nico-shimo/furima-32109#11]
#URL 
https://furima-32109.herokuapp.com/
- Basic認証
  - ID  'admin'  、 password  '2222'
- 出品者用のメールアドレス・パスワード
  - メールアドレス：'test@gmail'   パスワード： 'kuni102222'
- 購入者用のメールアドレス・パスワード
  - メールアドレス：'sample@gmail'　パスワード： 'kuni102222'
- 購入者用カードの番号・期限・セキュリティコード
  - カード番号：'4242424242424242' 、期限：'12/24'、セキュリティコード：'123'

**Comment by naru6117** [comment]
![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/49669977/101855451-c32c4380-3ba6-11eb-93b0-7b42e413c598.png)

nico-shimoさん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
